export default {
  CREATE_COURSE: 'CREATE_COURSE',
  LOAD_COURSES: 'LOAD_COURSES',
  UPDATE_COURSE: 'UPDATE_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  CREATE_TRAINER: 'CREATE_TRAINER',
  LOAD_TRAINERS: 'LOAD_TRAINERS',
  UPDATE_TRAINER: 'UPDATE_TRAINER',
  DELETE_TRAINER: 'DELETE_TRAINER'
};
